package com.ureca.snac.trade.entity;

public enum CancelReason {
    BUYER_CHANGE_MIND,
    BUYER_LIMIT_EXCEEDED,
    SELLER_CHANGE_MIND,
    SELLER_LIMIT_EXCEEDED,
    NOT_SELECTED,
    BUYER_FORCED_TERMINATION,
    SELLER_FORCED_TERMINATION,
    REAL_TIME_REPORTED,
    BUYER_CANNOT_RECEIVE,
    SELLER_CANNOT_SEND,
}
