spring:
  application:
    name: snac-server
  cloud:
    aws:
      credentials:
        access-key: ${AWS_SNS_ACCESS_KEY}
        secret-key: ${AWS_SNS_SECRET_KEY}
      region:
        static: ${REGION}
  jwt:
    secret: ${JWT_SECRET_KEY}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  rabbitmq:
    host: localhost
    port: 5672

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    with-credentials: true
    oauth2-redirect-url: /swagger-ui/oauth2-redirect.html


payments:
  toss:
    success-url: 1
    fail-url: 1

aes:
  passphrase: ${AES_PASSPHRASE}
  salt: ${AES_SALT}
